import re

def clean_response(text: str) -> str:
    """
    Cleans the AI response by removing </think> and special characters like \n
    """

    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    text = text.replace("\n", " ").strip()

    return text

text = """"<think>\nOkay, so I've got this query here where someone wants me to modify a paragraph by changing Lena's name to fit specific criteria: Grade 1, Hispanic, and male, who is interested in reading. They also mentioned that if necessary, pronouns can be changed.\n\nFirst, I need to understand the original paragraph. It describes Lena tiptoing into an old bookstore, finding a book with her name etched on it, and then seeing words written ahead of her as she reads. The goal is to make this more suitable for a first-grade Hispanic male who's interested in reading.\n\nLet me break down what needs to be done. The user wants the name changed, but only based on the instructions given—so just modifying Lena to fit the gender and ethnicity without altering the content too much.\n\nSince it's Grade 1, the language should be simple and appropriate for young children. Also, being Hispanic doesn't change the name much; perhaps using a common Hispanic male name would make sense. Maybe \"Ramiro\" or \"Daniel\"? I'll go with Ramiro because it sounds friendly and is often used in stories.\n\nNext, pronouns. The original paragraph uses \"she,\" which refers to Lena. Since we're changing to a male character, \"he\" should replace \"she.\" So the first sentence would be \"He tiptoed...\" instead of \"She tiptoed.\"\n\nNow, thinking about the reading part—since he's interested in reading, maybe adding an adjective like \"curious\" or \"eager\" could enhance his interest. Also, changing \"name etched on the cover\" to something more child-friendly, perhaps \"a sticker with his name\" would be better suited for a young kid.\n\nThe original paragraph says she flipped it open and saw words ahead of her eyes. Maybe adjusting that to show he's excited about reading or engaged can make it more engaging for him as a reader at that grade level.\n\nPutting it all together, I'll make sure the sentences are simple and clear, using actions that a first-grader might find exciting—like tiptoeing, finding something special, flipping a book, and becoming engrossed in reading. The changes should keep the story flowing while making it more relatable to a Hispanic male child.\n\nI also need to ensure that the pronouns are consistent throughout. So replacing \"she\" with \"he\" from the start will help maintain the gender consistency.\n\nFinally, reviewing each change to make sure it aligns with the user's instructions and maintains the original story's essence but in a way that's appropriate for the specified demographics.\n</think>\n\nHe tiptoed into the old bookstore, the scent of aged paper filling the air like a warm hug. Tucked between two dusty shelves, he found a tiny, leather-bound book with his name stuck to the cover. Heart pounding, he flipped it open—only to see the pages filled with words before his eyes. It was writing his story, one sentence ahead of him every move."""
print(clean_response(text))